Add RenderViewport Command
BYU-PCCL/holodeck-engine pull request #119
Opened 2018-11-27 18:02 UTC by jaydenmilne

Part of BYU-PCCL/holodeck#135

Add a command to toggle rendering the viewport

2018-11-27 20:53 UTC, nickwalton requested changes
I just noticed a couple style things, but besides that it looks great! Good work!

2018-11-27 20:53 UTC, nickwalton commented on Source/Holodeck/ClientCommands/Private/CommandFactory.cpp
> +										  {	"RenderViewport", &CreateInstance<URenderViewportCommand> } };
Nits: Just a small thing but align the renderviewport line with the others

2018-11-27 20:53 UTC, nickwalton commented on Source/Holodeck/ClientCommands/Private/RenderViewportCommand.cpp
> +	}
Another nits: The current style guide has the last brace of the if on the same line as the else. See here: https://github.com/BYU-PCCL/holodeck-engine/wiki/Style-Guide#code-blocks

2018-11-27 20:53 UTC, nickwalton commented on Source/Holodeck/ClientCommands/Private/RenderViewportCommand.cpp
> +	//		 This is basically what the command below does.
Did you mean to leave this in here?

2018-12-04 14:26 UTC, jaydenmilne commented on Source/Holodeck/ClientCommands/Private/RenderViewportCommand.cpp
> +	//		 This is basically what the command below does.
Yes, it's a warning for people who would want to copy this code

2018-12-04 14:30 UTC, merged