Default tasks
BYU-PCCL/holodeck-engine pull request #176
Opened 2019-05-31 20:52 UTC by MaxRobinsonTheGreat

- Fixed various problems with follow task
- Added avoid task, which returns a higher reward when the actor to avoid is farther away and full reward if the actor to avoid cannot see the agent
- Added functionality for the follow task to give a positive reward or negative reward when the location is reached, as well as an option to make it a terminal task

2019-06-03 16:09 UTC, jaydenmilne requested changes

2019-06-03 16:09 UTC, jaydenmilne commented on Source/Holodeck/Tasks/Private/AvoidTask.cpp
> +	if (FJsonSerializer::Deserialize(JsonReader, JsonParsed)) {
Should we log an error if we can't deserialize it? `UE_LOG(LogHolodeck, Fatal, TEXT("...` will log the error and crash the engine gracefully

2019-06-03 16:09 UTC, jaydenmilne commented on Source/Holodeck/Tasks/Private/DistanceTask.cpp
> +		if (JsonParsed->HasTypedField<EJson::Array>("GoalLocation")) {
Don't forget to update docs & config files https://holodeck.readthedocs.io/en/develop/packages/docs/tasks/distance-task.html

2019-06-03 16:09 UTC, jaydenmilne commented on Source/Holodeck/Tasks/Private/FollowTask.cpp
> +		if (JsonParsed->HasTypedField<EJson::String>("FollowSocket")) {
Don't forget to update docs https://holodeck.readthedocs.io/en/develop/packages/docs/tasks/follow-task.html

2019-06-03 16:09 UTC, jaydenmilne commented on Source/Holodeck/Tasks/Private/FollowTask.cpp
> +		if (JsonParsed->HasTypedField<EJson::String>("FollowSocket")) {
If we're going to do this then we should document what sockets are on the agents

2019-06-03 16:09 UTC, jaydenmilne commented on Source/Holodeck/Tasks/Private/FollowTask.cpp
> -		if (JsonParsed->HasTypedField<EJson::Number>("TargetHeight")) {
Don't forget to remove this from the docs

2019-06-03 16:09 UTC, jaydenmilne commented on Source/Holodeck/Tasks/Private/FollowTask.cpp
>  void UFollowTask::TickSensorComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) {
This code seems awfully similar to the new AvoidTask. Is there a way we could generalize it and have less code duplication between the two?

2019-06-03 16:09 UTC, jaydenmilne commented on Source/Holodeck/Tasks/Private/LocationTask.cpp
> +		if (JsonParsed->HasTypedField<EJson::String>("LocationActor")) {
Don't forget to update docs and configs https://holodeck.readthedocs.io/en/develop/packages/docs/tasks/distance-task.html

2019-06-03 16:09 UTC, jaydenmilne commented on Source/Holodeck/Tasks/Private/LocationTask.cpp
> +float ULocationTask::CalcDistance() {
This function seems to be duplicated in three places. Maybe make a helper class?

2019-06-05 22:17 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/Tasks/Private/AvoidTask.cpp
> +	if (FJsonSerializer::Deserialize(JsonReader, JsonParsed)) {
Added logging

2019-06-05 22:18 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/Tasks/Private/DistanceTask.cpp
> +		if (JsonParsed->HasTypedField<EJson::Array>("GoalLocation")) {
Updated

2019-06-05 22:19 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/Tasks/Private/FollowTask.cpp
> -		if (JsonParsed->HasTypedField<EJson::Number>("TargetHeight")) {
Removed

2019-06-05 22:20 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/Tasks/Private/FollowTask.cpp
>  void UFollowTask::TickSensorComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) {
A few key differences make this code complicated to generalize, but some common functionality has been moved to a helper class

2019-06-05 22:21 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/Tasks/Private/LocationTask.cpp
> +		if (JsonParsed->HasTypedField<EJson::String>("LocationActor")) {
updated

2019-06-05 22:24 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/Tasks/Private/LocationTask.cpp
> +float ULocationTask::CalcDistance() {
The actual duplication is the subtraction bit, which I think is simple enough that it doesn't need to be moved to its own function. Getting the start location and end location are actually fairly different between different tasks and shouldn't be generalized in the helper class

2019-06-19 21:25 UTC, jaydenmilne commented
#250

2019-06-20 16:39 UTC, jaydenmilne approved these changes

2019-06-20 16:48 UTC, merged