Fix/semaphore release
BYU-PCCL/holodeck-engine pull request #202
Opened 2020-01-31 20:51 UTC by daniekpo

Updated the semaphore unlink code to only unlink semaphores that were created/used by this process. Added memory cleanup code (review needed here). This should resolve #341

2020-02-07 00:44 UTC, MaxRobinsonTheGreat requested changes
I did not know about errno. Cool!

2020-02-07 22:33 UTC, MaxRobinsonTheGreat approved these changes
looks amazing

2020-02-07 22:42 UTC, jaydenmilne commented on Source/Holodeck/HolodeckCore/Private/HolodeckServer.cpp
> +	if (errno == EACCES || errno == EEXIST || errno == EINVAL || errno == EMFILE || errno == ENFILE) {
Instead of clearing errno and checking it every time, you should be checking to see if the result of `sem_open` is `SEM_FAILED` (acccording to the man page http://man7.org/linux/man-pages/man3/sem_open.3.html)

2020-02-26 20:38 UTC, daniekpo commented on Source/Holodeck/HolodeckCore/Private/HolodeckServer.cpp
> +	if (errno == EACCES || errno == EEXIST || errno == EINVAL || errno == EMFILE || errno == ENFILE) {
Done

2020-03-04 18:31 UTC, vinhowe approved these changes
As far as I can tell, this looks good.

2020-03-05 16:22 UTC, jaydenmilne requested changes
It seems your editor is set to use spaces instead of tabs, which leads to some alignment problems. UE4 style guide is to use tabs set at 4 spaces: https://docs.unrealengine.com/en-US/Programming/Development/CodingStandard/index.html

Just some minor formatting stuff and it should be good to go!

2020-03-05 16:22 UTC, jaydenmilne commented on Source/Holodeck/HolodeckCore/Private/HolodeckServer.cpp
> +    if (LockingSemaphore1 == SEM_FAILED) {
Can you fix the indentation here?

2020-03-05 16:22 UTC, jaydenmilne commented on Source/Holodeck/HolodeckCore/Private/HolodeckServer.cpp
> +    if (LockingSemaphore2 == SEM_FAILED) {
Indentation

2020-03-05 16:22 UTC, jaydenmilne commented on Source/Holodeck/HolodeckCore/Public/HolodeckServer.h
> +    #endif
Indentation

2020-03-05 16:22 UTC, jaydenmilne commented on Source/Holodeck/HolodeckCore/Public/HolodeckSharedMemory.h
> +    #endif
Fix indentation

2020-03-17 23:06 UTC, daniekpo commented on Source/Holodeck/HolodeckCore/Private/HolodeckServer.cpp
> +    if (LockingSemaphore1 == SEM_FAILED) {
Done

2020-03-17 23:06 UTC, daniekpo commented on Source/Holodeck/HolodeckCore/Private/HolodeckServer.cpp
> +    if (LockingSemaphore2 == SEM_FAILED) {
Done

2020-03-17 23:06 UTC, daniekpo commented on Source/Holodeck/HolodeckCore/Public/HolodeckServer.h
> +    #endif
Done

2020-03-17 23:07 UTC, daniekpo commented on Source/Holodeck/HolodeckCore/Public/HolodeckSharedMemory.h
> +    #endif
Done

2020-03-19 16:54 UTC, jaydenmilne approved these changes

2020-03-25 19:05 UTC, merged