Add min and max to all agents
BYU-PCCL/holodeck-engine pull request #203
Opened 2020-02-19 22:51 UTC by daniekpo

Moved constants to the corresponding .h files. Added min and max constraints to some agents so that all agents have constraints. Related to [holodeck issue 369](https://github.com/BYU-PCCL/holodeck/issues/369)

2020-03-05 16:29 UTC, jaydenmilne reviewed
I trust that you've run the tests to verify behavior hasn't changed significantly. This is also going to need good docs & a message in the changelog.

It would be tricky but some kind of basic test to validate this behavior would be nice too.

2020-03-05 16:29 UTC, jaydenmilne commented on Source/Holodeck/Agents/Private/NavAgent.cpp
> +	float x = FMath::Clamp(CommandArray[0], MIN_DISTANCE, MAX_DISTANCE);
I don't think we really need this for the NavAgent since it's not intended to be used to train with. Thoughts @MaxRobinsonTheGreat?

2020-03-05 16:29 UTC, jaydenmilne commented on Source/Holodeck/Agents/Public/Android.h
> +	static constexpr float MAX_TORQUE = 30.0f;
Where did you get these numbers from? Just curious

2020-03-05 16:29 UTC, jaydenmilne commented on Source/Holodeck/Agents/Public/NavAgent.h
> +static float MAX_DISTANCE = 0.5;
Missing `constexpr`? Am I forgetting something?

2020-03-05 16:29 UTC, jaydenmilne commented on Source/Holodeck/Agents/Public/TurtleAgent.h
> +static constexpr  float MAX_THRUST = 160.0f;
Fix spacing

2020-03-17 22:45 UTC, daniekpo commented on Source/Holodeck/Agents/Private/NavAgent.cpp
> +	float x = FMath::Clamp(CommandArray[0], MIN_DISTANCE, MAX_DISTANCE);
@MaxRobinsonTheGreat could you take a look at this when you can?

2020-03-17 22:48 UTC, daniekpo commented on Source/Holodeck/Agents/Private/NavAgent.cpp
> +	float x = FMath::Clamp(CommandArray[0], MIN_DISTANCE, MAX_DISTANCE);
I think you're right @jaydenmilne. My initial thought was to add normalization to every agent.

2020-03-17 22:50 UTC, daniekpo commented on Source/Holodeck/Agents/Public/Android.h
> +	static constexpr float MAX_TORQUE = 30.0f;
From one of the other agents. @MaxRobinsonTheGreat said to use numbers that made sense so I figured I'd use something that was already used.

2020-03-17 22:51 UTC, daniekpo commented on Source/Holodeck/Agents/Public/NavAgent.h
> +static float MAX_DISTANCE = 0.5;
We were not using it in the context that `constexpr` would be beneficial so I figured we don't need it.

2020-03-18 00:46 UTC, MaxRobinsonTheGreat approved these changes
Looks good to me.

2020-03-19 16:56 UTC, jaydenmilne requested changes

2020-03-19 16:56 UTC, jaydenmilne commented on Source/Holodeck/Agents/Private/NavAgent.cpp
> +	float x = FMath::Clamp(CommandArray[0], MIN_DISTANCE, MAX_DISTANCE);
Wait and this x,y,z isn't even a distance it is a location, so this clamiping is going to cause issues. I'd get rid of it

2020-03-31 17:19 UTC, jaydenmilne approved these changes

2020-03-31 17:20 UTC, merged