Abuse sensor
BYU-PCCL/holodeck-engine pull request #206
Opened 2020-03-07 01:20 UTC by MaxRobinsonTheGreat

BYU-PCCL/holodeck#262

2020-03-10 17:37 UTC, jaydenmilne requested changes

2020-03-10 17:37 UTC, jaydenmilne commented on Source/Holodeck/Agents/Public/Android.h
> +	float GetAccelerationLimit() override { return 200; }
Where did you get these number from? Can you add a comment?

2020-03-11 00:21 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/Agents/Public/Android.h
> +	float GetAccelerationLimit() override { return 200; }
Well.. I kinda just pulled them out of thin air. 🤷‍♂ I added some comments on why I chose those numbers, but I couldn't find any info on maximum fall distance for roombas or uavs from user manuals, so I just went with intuition.

2020-03-12 15:22 UTC, jaydenmilne commented on Source/Holodeck/Agents/Public/Android.h
> +	float GetAccelerationLimit() override { return 200; }
OK. Did you drop them from different heights and measure the impact? That might be a good proxy, just do some experiments

2020-03-12 18:02 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/Agents/Public/Android.h
> +	float GetAccelerationLimit() override { return 200; }
Yes, the added comments show the maximum height they can be dropped from and I found this by playing around with various drop heights and seeing how much acceleration it caused.

2020-03-19 16:49 UTC, jaydenmilne commented on Source/Holodeck/Agents/Public/Android.h
> +	float GetAccelerationLimit() override { return 200; }
aight

2020-03-19 16:53 UTC, jaydenmilne approved these changes
LGTM, 10/10 great work

2020-03-26 04:42 UTC, merged