Rangefinder
BYU-PCCL/holodeck-engine pull request #207
Opened 2020-03-10 23:15 UTC by kolbytn

Added RangeFinderSensor and logic.

2020-03-11 00:26 UTC, MaxRobinsonTheGreat approved these changes
👍

2020-03-12 15:36 UTC, jaydenmilne requested changes

2020-03-12 15:36 UTC, jaydenmilne commented on Source/Holodeck/Sensors/Public/RangeFinderSensor.cpp
> +		if (JsonParsed->HasTypedField<EJson::Number>("LazerCount")) {
Uhh, bad news, it's spelled "laser"

¯\\_(ツ)_/¯

2020-03-12 15:36 UTC, jaydenmilne commented on Source/Holodeck/Sensors/Public/RangeFinderSensor.cpp
> +			DrawDebugLine(GetWorld(), start, end, FColor::Green, false, .01, ECC_WorldStatic, 1.f);
Did you get rid of the ghosting problem?

2020-03-12 15:36 UTC, jaydenmilne commented on Source/Holodeck/Sensors/Public/RangeFinderSensor.h
> + * By default the sensor retruns one number that represents the distance to
s/retruns/returns

2020-03-17 22:44 UTC, daniekpo approved these changes
Looks good to me apart from the spelling mistakes @jaydenmilne  suggested.

2020-03-18 14:53 UTC, kolbytn commented on Source/Holodeck/Sensors/Public/RangeFinderSensor.cpp
> +		if (JsonParsed->HasTypedField<EJson::Number>("LazerCount")) {
Well it should be spelled lazer.... Lazer is much better...

2020-03-18 14:54 UTC, kolbytn commented on Source/Holodeck/Sensors/Public/RangeFinderSensor.cpp
> +			DrawDebugLine(GetWorld(), start, end, FColor::Green, false, .01, ECC_WorldStatic, 1.f);
Yes. Shortening the duration time significantly solved the problem.

2020-03-19 16:49 UTC, jaydenmilne approved these changes

2020-03-19 17:36 UTC, merged