Fix build
BYU-PCCL/holodeck-engine pull request #211
Opened 2020-03-24 18:27 UTC by jaydenmilne

Clang doesn't like comparing a float to a null
(http://monster.cs.byu.edu/blue/organizations/jenkins/holodeck-engine/detail/develop/64/pipeline/)

2020-03-24 21:23 UTC, kolbytn requested changes
See comment. I'm not sure if the hit result might legitimately return zero if the collision was right on the agent.

2020-03-24 21:23 UTC, kolbytn commented on Source/Holodeck/Sensors/Private/RangeFinderSensor.cpp
> +		FloatBuffer[i] = (Hit.Distance != 0 ? Hit.Distance : LaserMaxDistance) / 100;  // centimeter to meters
Actually now that I'm looking at it I think `FloatBuffer[i] = (TraceResult ? Hit.Distance : LaserMaxDistance) / 100;` would make more sense. Just in case there is some case when the sensor legitimately returns 0. We would just have to rerun the unit tests to make sure `TraceResult` returns what we think it does.

2020-03-31 15:38 UTC, jaydenmilne commented on Source/Holodeck/Sensors/Private/RangeFinderSensor.cpp
> +		FloatBuffer[i] = (Hit.Distance != 0 ? Hit.Distance : LaserMaxDistance) / 100;  // centimeter to meters
Tests pass with this change. I'll ship it

2020-03-31 16:58 UTC, kolbytn approved these changes

2020-03-31 16:59 UTC, merged