Max height
BYU-PCCL/holodeck-engine pull request #216
Opened 2020-10-30 23:15 UTC by chris-luangrath

In order for this to work, also needs edits from the max-height branch in BYU-PCCL/holodeck (the python/json side)

HolodeckAgent.h - GetMaxHeight function and MaxHeight float
I feel like I should change how it’s implemented. I just kinda put it there, and I feel like it’s doing its own thing.

HolodeckGameMode.h - Updated SpawnAgent function

SpawnAgentCommand.cpp - Changed IsMainAgent = NumberParams[6] to [7] 
(I’m kinda not sure where I changed that made it like this tbh, but I edited the code to make it work. Should I find a way to make it 7 again, or does it not matter?)
float MaxHeight = NP[6] (Same concern as [6] to [7])
Updated SpawnAgent call to include MaxHeight
MaxHeight is now a var in SpawnAgent

Uav.cpp
SetMaxHeight(GetMaxHeight())
SetMaxHeight function
I feel like I *could* consolidate SetMaxHeight into MaxHeightCeiling, but I wouldn't want to add another line of code to run every tick when it only needs to run once
MaxHeightCeiling function teleports the Uav to the maxHeight-1 if it's above the maxHeight

2020-11-02 22:42 UTC, MaxRobinsonTheGreat requested changes

2020-11-02 22:42 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/ClientCommands/Private/SpawnAgentCommand.cpp
> +	verifyf(StringParams.size() == 2 && NumberParams.size() <= 8, TEXT("%s: Bad Arguments"), *FString(__func__)); // NumberParams.size() used to be == 7
shouldn't it be `==8` now then?

2020-11-02 22:42 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/ClientCommands/Private/SpawnAgentCommand.cpp
> +	bool IsMainAgent = (bool) NumberParams[7]; // used to be 6, now is 7
You don't need the comment here

2020-11-02 22:42 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/Agents/Private/Uav.cpp
> +	SetMaxHeight(GetMaxHeight());
Why isn't SetMaxHeight being called here and not in the spawn agent command?

2020-11-02 22:42 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/Agents/Public/Uav.h
> +	float maxHeight;
You have a maxHeight variable for the uav and a MaxHeight for its parent class HolodeckAgent. You only need the parent class one.

2020-11-02 22:42 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/HolodeckCore/Public/HolodeckAgent.h
> +	virtual float GetMaxHeight();
Doesn't need to be virtual since the child classes aren't overriding it.

2020-11-02 22:43 UTC, MaxRobinsonTheGreat commented
Also, we're merging into develop, not master.

2020-11-05 04:08 UTC, chris-luangrath reviewed
Everything should be fixed now.

2020-11-11 20:32 UTC, MaxRobinsonTheGreat requested changes, later dismissed

2020-11-11 20:32 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/ClientCommands/Private/SpawnAgentCommand.cpp
> +	float MaxHeight = NumberParams[6];
Convert to cm by multiplying by 100 here.

2020-11-11 20:32 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/HolodeckCore/Private/HolodeckAgent.cpp
> +	if (GetActorLocation().Z > MaxHeight - 1) {
Why -1?

2020-11-11 20:32 UTC, MaxRobinsonTheGreat commented on Source/Holodeck/HolodeckCore/Public/HolodeckGameMode.h
> +	AHolodeckAgent* SpawnAgent(const FString& Type, const FVector& Location, const FRotator& Rotation, const FString& Name, bool IsMainAgent, float MaxHeight);
Shouldn't there be a change to the holodeckgamemode blueprint file in this pr?
Also, can you remove the changes to the example level map? You can do that with git

2021-01-09 23:50 UTC, vinhowe commented
@MaxRobinsonTheGreat Did all of your comments get resolved?

2021-01-19 21:21 UTC, vinhowe requested changes

2021-01-19 21:21 UTC, vinhowe commented on Source/Holodeck/Agents/Private/Uav.cpp
> +
Did we verify that this makes a difference?

2021-01-19 21:21 UTC, vinhowe commented on Source/Holodeck/ClientCommands/Private/SpawnAgentCommand.cpp
> +	float MaxHeight = (NumberParams[6] * 100);// -11.8283691; // *100 to convert to centimeters, and for whatever reason, subtracting 11.8... makes it more accurate. Could be height of
If we're not subtracting here, can we remove the comment?

2021-01-19 22:23 UTC, vinhowe approved these changes
Looks good to me

2021-01-19 22:28 UTC, daniekpo approved these changes
LGTM! Good work!

2021-04-28 23:43 UTC, merged