Fix imu sensor
BYU-PCCL/holodeck-engine pull request #219
Opened 2020-12-18 23:15 UTC by mattpow35

Don't forget to update the readme in the holodeck repo :)
This is related to issue BYU-PCCL/holodeck#437

2021-01-20 22:09 UTC, vinhowe commented on Source/Holodeck/Sensors/Private/IMUSensor.cpp
> +	VelocityNow = Parent->GetPhysicsLinearVelocity();
This looks right. On first glance it doesn't look like we have any tests that handle this.

2021-01-20 22:11 UTC, vinhowe commented on enc_temp_folder/347cdf8dc515add4ee3f91e33ca8de5/IMUSensor.cpp
> +// MIT License (c) 2019 BYU PCCL see LICENSE file
This looks like an auto-save file left behind by Visual Studio. Can you remove it?

2021-01-20 22:15 UTC, vinhowe requested changes
Will you revert your changes to `ExampleLevel.umap` and `ExampleLevel_BuiltData.uasset`?

I'll ask @daniekpo but I don't think we have any tests that specifically handle the IMU sensor (I just looked), which means we don't have any tests to break but I guess we haven't specified any correct behavior either.

2021-01-22 01:23 UTC, daniekpo commented
> Will you revert your changes to `ExampleLevel.umap` and `ExampleLevel_BuiltData.uasset`? I think the fastest way is just `git checkout develop <path/to/ExampleLevel.umap> <path/to/ExampleLevel_BuiltData.uasset>`.
> 
> I'll ask @daniekpo but I don't think we have any tests that specifically handle the IMU sensor (I just looked), which means we don't have any tests to break but I guess we haven't specified any correct behavior either.

Yeah, I don't think we have a test for the IMU sensor.

2021-01-22 01:24 UTC, daniekpo commented
And, I'd revert the changes made to the asset files as @vinhowe recommended. I don't think you meant to make those changes.

2021-01-27 18:53 UTC, mattpow35 commented on enc_temp_folder/347cdf8dc515add4ee3f91e33ca8de5/IMUSensor.cpp
> +// MIT License (c) 2019 BYU PCCL see LICENSE file
Good catch, I removed it.

2021-01-27 18:54 UTC, mattpow35 commented
I also did not see any tests for this, it would be a good idea to make some to make sure it works.

2021-01-27 19:30 UTC, vinhowe commented on enc_temp_folder/347cdf8dc515add4ee3f91e33ca8de5/IMUSensor.cpp
> +#include "Holodeck.h"
Can you get rid of this entire file? It looks like it's a autosaved copy of the file we're interested in.

2021-01-27 19:35 UTC, mattpow35 commented on enc_temp_folder/347cdf8dc515add4ee3f91e33ca8de5/IMUSensor.cpp
> +#include "Holodeck.h"
Ya I will, my bad, I thought the last comment was only talking about the first line. 
Should I delete the entire directory named enc_temp_folder? this file seems to be the only thing in there

2021-01-27 19:37 UTC, vinhowe commented on enc_temp_folder/347cdf8dc515add4ee3f91e33ca8de5/IMUSensor.cpp
> +#include "Holodeck.h"
I went ahead and pushed https://github.com/BYU-PCCL/holodeck-engine/pull/219/commits/372471ac4020cd6d4eb8f5e3e5af75b20f1f35ac, which should take care of it.

2021-01-27 19:39 UTC, mattpow35 commented on enc_temp_folder/347cdf8dc515add4ee3f91e33ca8de5/IMUSensor.cpp
> +#include "Holodeck.h"
sweet

2021-01-27 19:39 UTC, vinhowe approved these changes
This looks good to me. @daniekpo do we want to block this until we have tests on the client? Seems to me like we could just go ahead and merge.

2021-02-03 22:23 UTC, daniekpo commented
> This looks good to me. @daniekpo do you want to block this until we have tests on the client? Seems to me like we could just go ahead and merge.

I think we can just merge it.

2021-02-24 19:55 UTC, merged