Fix shared memory size of "command_buffer"
BYU-PCCL/holodeck-engine pull request #220
Opened 2021-01-14 04:10 UTC by AdrianSchoisengeier

If I'm not mistaken, Server->Malloc() takes the buffer size in bytes, not bits. So the whole constant UCommandCenter::BYTE_SIZE is not needed (or at the least, the constant should be equal to 1, not 8).
From what I see on my machine, the engine currently allocates 8 times too much memory for "command_buffer", when compared to the client. (engine: 8388608 vs. client: 1048576). This changes fixes that.

2021-01-20 22:31 UTC, vinhowe approved these changes
Thanks for contributing @AdrianSchoisengeier! It looks like you're totally right here. Not sure why we were doing this. Here's the relevant line from our documentation for Server->Malloc():
https://github.com/BYU-PCCL/holodeck-engine/blob/510d306147e88ec5d552f467b4451bc21dcd04f9/Source/Holodeck/HolodeckCore/Public/HolodeckServer.h#L79

@daniekpo I'm going to run our tests just to make sure we weren't somehow depending on the larger buffer size.

2021-01-22 01:31 UTC, daniekpo reviewed
I checked the documentation on the Linux and Windows side and @AdrianSchoisengeier is right here. We need to merge this to the `develop` branch though after running the tests. Thanks for the contribution!

2021-01-22 01:38 UTC, daniekpo commented
@AdrianSchoisengeier looks like you branched off of the master branch. Could you merge your branch with the `develop` branch? We push changes to `develop` since `master` is our release branch. Thanks!

2021-01-22 01:39 UTC, daniekpo requested changes
Merge with the `develop` branch.

2021-01-22 02:51 UTC, AdrianSchoisengeier commented
Done.
(At least I think so... Let me know if anything is wrong. I did this whole pull request from the browser without cloning the repo)

2021-01-22 03:43 UTC, daniekpo approved these changes
LGTM!

2021-01-22 19:37 UTC, vinhowe commented
Good catch on merging develop. We should be good to test this now.

2021-01-23 01:42 UTC, merged