Command center
BYU-PCCL/holodeck-engine pull request #56
Opened 2018-03-22 18:09 UTC by mitchneutron

Created the command center class. It opens up and manages a path of communication from the client to the Holodeck, and executes commands found in the buffer. The buffer is expected to be in UTF-8 JSON format. 

Alongside that, I created a SpawnAgent command.

2018-03-22 19:03 UTC, joshgreaves requested changes
Really great job! This is a significant contribution, thanks for doing this. Good object oriented design, and excellent self documenting code.

I didn't review to the end, could you do a couple of style related things generally to the code to help with readability:
1) I added some more lines to the styleguide https://github.com/BYU-PCCL/Holodeck/wiki/Style-Guide can you please look subheading for code blocks and apply it throughout.
2) As I mentioned, your code is really readable. Generally it is clear to see what you are doing, and comments get in the way a little. Please can you remove any comments where it is clear what you are doing.

I'll review again after those changes.
Thanks!

2018-03-22 19:03 UTC, joshgreaves commented on Source/Holodeck/Agents/Private/HolodeckUAVController.cpp
> +	}
Nits:
} else {
And remove extra whitespace in else statement

2018-03-22 19:03 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/Command.cpp
> +void UCommand::Init(std::vector<float> NumberParameters, std::vector<std::string> StringParameters, AActor* ParameterTarget) {
When passing parameters you won't be mutating, use constant references.
e.g. const std::vector<float>& NumberParameters

2018-03-22 19:03 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +	if (Input == nullptr) {
Simpler to write:
.... {
if (Input != nullptr)
  Commands.add(Input)
}

2018-03-22 19:03 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +
Nits: unnecessary whitespace

2018-03-22 19:03 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +	//execute all of the commands that you found, plus any that were given to you.
The comments in this function aren't needed, it is very clear what you are doing. Good self documenting code!
And nits: curly braces not needed for one line block

2018-03-22 19:03 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +		return;
unnecessary return here.

2018-03-26 21:43 UTC, mitchneutron commented
@joshgreaves I fixed everything up, double checked everything, and I think that all of the styling should be good to go.

2018-03-27 17:55 UTC, joshgreaves requested changes
Once again, nice job! Well done on including the MIT license to the gason files. A lot of really good code here.

The last general thing is the use of constants where they're needed, especially in constant references as parameters.

2018-03-27 17:55 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +void UCommandCenter::GiveCommand(UCommand* &Input) {
Shouldn't have pointer reference, should have * const

2018-03-27 17:55 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +	bool* BoolPtr = static_cast<bool*>(ShouldReadBufferPtr);
It may be better to store the ShouldReadBufferPtr as a bool*, then we can avoid casting it each tick. What do you think?

2018-03-27 17:55 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +	for (int i = 0; i < Commands.Num(); i++)
Can you do a range based for loop here?

2018-03-27 17:55 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +		*BoolPtr = false;
For safety, can you check it isn't a null pointer and log an error if it is a null pointer.

2018-03-27 17:55 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +void UCommandCenter::ExtractCommandsFromJson(JsonValue Input){
Can this be a const reference?

2018-03-27 17:55 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +	case JSON_NUMBER: {
Cases don't need curly braces. Better format would be:
case JSON_STRING:
    std::string...
    FString...
    UE_LOG...
    break;
case...

2018-03-27 17:55 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +		for (auto i : Value) {
const auto& i

2018-03-27 17:55 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandFactory.cpp
> +	if (Name == SPAWN_AGENT) {
I think as we scale up the number of commands we have this will be slower than we'd like. An implementation like this could be nicer https://stackoverflow.com/questions/582331/is-there-a-way-to-instantiate-objects-from-a-string-holding-their-class-name
What do you think?

2018-03-27 17:55 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/SpawnAgentCommand.cpp
> +const static FString SphereRobotReference = "Blueprint'/Game/HolodeckContent/Agents/SphereRobot/SphereRobotBlueprint.SphereRobotBlueprint'";
Missing NavAgent

2018-03-27 17:55 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/SpawnAgentCommand.cpp
> +bool USpawnAgentCommand::bFirstInstance = true;
Prefer use static variable over global variable. Also, for the above subclasses. Generally, global constants are fine.

2018-03-27 17:55 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/SpawnAgentCommand.cpp
> +			UE_LOG(LogHolodeck, Warning, TEXT("SpawnAgentCommand unable to find UAV blueprint"));
nits: I think this would be more readable if there were a blank line between each if else pair. What do you think?

2018-03-27 17:55 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/SpawnAgentCommand.cpp
> +	else
else if on one line

2018-03-27 17:55 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/SpawnAgentCommand.cpp
> +	else
On second thoughts, each line of the code looks the same. Could we use a map from AgentType of AUAV, AAndroid, ASphereRobot?

2018-03-27 17:55 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Public/CommandCenter.h
> +	FString BUFFER_NAME = "command_buffer";
Can these be const statics?

2018-03-27 19:31 UTC, mitchneutron commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +	case JSON_NUMBER: {
To declare the variable inside the switch statement I need to define a namespace for the case. I can either move the variable declaration to the beginning of the function or I'll have to keep the braces. I think it's better to not needlessly instantiate the variable. What do you think? I'll for sure take the braces off of the other cases though.

2018-03-27 19:43 UTC, mitchneutron commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +void UCommandCenter::GiveCommand(UCommand* &Input) {
Done

2018-03-27 19:43 UTC, mitchneutron commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +	bool* BoolPtr = static_cast<bool*>(ShouldReadBufferPtr);
Agreed.

2018-04-02 22:45 UTC, joshgreaves reviewed
I'm halfway through the review, I'll check the rest in a bit. One thing that would be good is to break some of the logging you do around json into different levels to stop it from filling up the log. https://wiki.unrealengine.com/Logs,_Printing_Messages_To_Yourself_During_Runtime
a good level might be verbose or very verbose.

2018-04-02 22:45 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +void UCommandCenter::Init(UHolodeckServer* ParameterServer, AHolodeckGameMode* ParameterGameMode) {
Could you make these constant pointers please.

2018-04-02 22:45 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +	int Status = jsonParse(Buffer, &Endptr, &Value, Allocator);
Is this correct? You're passing a pointer to a pointer, did you mean to do that?

2018-04-02 22:45 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +void const UCommandCenter::PrintJson(JsonValue Value) {
Could this be a const reference?

2018-04-02 22:45 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +					  break;
break should have the same indent as the previous line.

2018-04-02 22:45 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +	case JSON_STRING: {
Don't need curly braces here

2018-04-03 17:55 UTC, mitchneutron commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +	int Status = jsonParse(Buffer, &Endptr, &Value, Allocator);
Yes, this is correct. It is declared as a pointer to a pointer in the gason.h file. It ends up turning endptr into a pointer to the end of the written buffer.

2018-04-10 16:14 UTC, MaxRobinsonTheGreat approved these changes
This is very cool. Everything looks in order and I  think its good to go.

2018-04-10 17:27 UTC, joshgreaves reviewed
Looks good, just respond to these last comments and then it should be good to go.

2018-04-10 17:27 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +	case JSON_NUMBER:
Nits: everything inside the switch needs an extra level of indent.

2018-04-10 17:27 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +		for (auto i : Value) {
Can this be const &?

2018-04-10 17:27 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +void const UCommandCenter::PrintJson(const JsonValue& Value) {
This function isn't really a CommandCenter thing. Do you think we should add it to the JSON files? Or somewhere else?

2018-04-10 17:27 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandFactory.cpp
> +UCommand* UCommandFactory::MakeCommand(const std::string& Name, std::vector<float> NumberParameters, std::vector<std::string> StringParameters, AActor* ParameterGameMode) {
It looks like NumberParameters and StringParameters can be const &

2018-04-10 17:27 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/CommandFactory.cpp
> +	}
nits: } else

2018-04-10 17:27 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Private/SpawnAgentCommand.cpp
> +}
Nits: Need blank line at end of file.

2018-04-10 17:27 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Public/Command.h
> +	const virtual void Execute() { check( 0 && "You must override UCommand::Execute" ); };
What is const doing here?

2018-04-10 17:27 UTC, joshgreaves commented on Source/Holodeck/ClientCommands/Public/CommandFactory.h
> +template<typename T> UCommand * CreateT() { return new T; }
What is this for? It looks dangerous to allocate memory with new in this way.

2018-04-10 17:27 UTC, joshgreaves commented on Source/Holodeck/HolodeckCore/Private/HolodeckAgent.cpp
> +	if(bControllerInitializationSuccessful)
if (InitializeController())

2018-04-11 21:47 UTC, mitchneutron commented on Source/Holodeck/ClientCommands/Public/CommandFactory.h
> +template<typename T> UCommand * CreateT() { return new T; }
Right, that is a line I missed in my code clean up.

2018-04-11 21:51 UTC, mitchneutron commented on Source/Holodeck/ClientCommands/Public/Command.h
> +	const virtual void Execute() { check( 0 && "You must override UCommand::Execute" ); };
My thoughts were that the executing the command doesn't alter the command, just performs it. What do you think, should I take out the const?

2018-04-11 21:58 UTC, mitchneutron commented on Source/Holodeck/ClientCommands/Private/CommandCenter.cpp
> +void const UCommandCenter::PrintJson(const JsonValue& Value) {
Yeah, I'll move it to the JSON files.  It was just my convenience at the time to write it here.

2018-04-12 18:26 UTC, closed without merging