Added implementation for Agent Hyper Parameters
BYU-PCCL/holodeck-engine pull request #62
Opened 2018-04-13 21:19 UTC by mitchneutron

2018-04-17 17:13 UTC, MaxRobinsonTheGreat approved these changes
Looks good

2018-04-24 15:37 UTC, joshgreaves requested changes
Nice job! There are two things I have questions about:
1) Why is the memcpy necessary? I thought we discussed writing the default values directly into the buffer, and then reading directly from that buffer? Also, it could be nice to extract that into a function like ResetHyperparameters which would do this, so that the user could specify a return to the default hyperparameters.
2) Is there a way for the user to update the PID controllers? They are calibrated at begin play, but then never set again, even if the values change. Perhaps we also need a bool to signify that the hyperparameters have changed to initiate an update to the PID controllers.

We may also want to put this in the controller at some point since we are going to remove HolodeckAgents. But we can look at doing that later.

2018-04-24 15:37 UTC, joshgreaves commented on Source/Holodeck/Agents/Public/UAV.h
> +	int GetHyperParameterCount() const override;
Nits: Hyperparameter is one word. Also, other function names should change that.

2018-04-24 15:37 UTC, joshgreaves commented on Source/Holodeck/Agents/Private/UAV.cpp
> +enum AUAV::ParameterIndeces {
Why does the enum start at 1 instead of 0?
Also, I think the NUMBER_OF_PARAMETERS would fit better as its own const int.

2018-04-24 15:37 UTC, joshgreaves commented on Source/Holodeck/Agents/Private/UAV.cpp
> +	const float* const HyperParametersPointer = GetHyperParameters();
It would be nice to cache this.

2018-04-26 14:58 UTC, mitchneutron commented on Source/Holodeck/Agents/Private/UAV.cpp
> +enum AUAV::ParameterIndeces {
I can see how it's unclear. I was thinking that the first "hyperparameter" would be the number of items in the array. I should have included that in the enum.

2018-05-05 14:33 UTC, merged

2018-06-18 23:03 UTC, nickwalton commented
Are we good to delete this branch?