Change HolodeckAgent to HolodeckAgentInterface
BYU-PCCL/holodeck-engine pull request #72
Opened 2018-05-03 23:07 UTC by nickwalton

I created the changes for the AgentInterface so that the nav agent inherits from the character class. It added a lot of changes so I'm sure there are things that could be better.

2018-05-05 15:44 UTC, mitchneutron requested changes
Good job on getting the interface working! It seems well written. I just have one question about the functions that are implemented in each of the agents. I know that Unreal Engine has funky constraints on the interfaces, and I haven't read enough to know better, but is it possible to put the implementation into the interface instead of having the same code in lots of the agents?

2018-05-05 15:44 UTC, mitchneutron commented on Source/Holodeck/Agents/Private/Android.cpp
> +bool AAndroid::Teleport_Implementation(const FVector& NewLocation) {
Can the implementation for the teleports and InitializeController go into the interface since it's the same for all of the agents?

2018-05-05 15:44 UTC, mitchneutron commented on Source/Holodeck/Agents/Private/NavAgent.cpp
> +}
Newline here

2018-08-31 20:58 UTC, nickwalton commented
Decided that we won't use this method.

2018-08-31 20:58 UTC, closed without merging