Updated camera
BYU-PCCL/holodeck-engine pull request #74
Opened 2018-06-12 01:11 UTC by nickwalton

Adds Holodeck Camera class which can enable any number of agents to have cameras. Optimizations have been made to increase the speed from previous attempts by bypassing the "ReadPixels" function and reading from the GPU without performing a gpu flush.

2018-06-12 03:02 UTC, mitchneutron requested changes
As far as your logic and actual code, it looks great. The workaround is awesome. The only architecture concern I have is with the  camera's capture being called from the viewport object instead of just in the tick function. I'm unsure if it's still necessary (it might be!) with the workaround you did. It would be best if we could avoid that dependency. 

Other than that, just nits for the style guide. Maybe we can talk about loosening it up a little? I think it does have value to strictly follow it though.

2018-06-12 03:02 UTC, mitchneutron commented on Source/Holodeck/General/Private/HolodeckViewportClient.cpp
> +	UE_LOG(LogHolodeck, Log, TEXT("@@@@@ Draw called"));
We should take out these debug statements so they don't clutter up the log.

2018-06-12 03:02 UTC, mitchneutron commented on Source/Holodeck/General/Private/HolodeckViewportClient.cpp
> +	UE_LOG(LogHolodeck, Log, TEXT("@@@@@ Draw Ended"));
This one too

2018-06-12 03:02 UTC, mitchneutron commented on Source/Holodeck/General/Private/HolodeckViewportClient.cpp
> +	UE_LOG(LogHolodeck, Log, TEXT("@@@@@ Draw called"));
Also, considering the workaround you did with not flushing the rendering thread, is it still necessary for us to capture the pixels at the time that the viewport renders?

2018-06-12 03:02 UTC, mitchneutron commented on Source/Holodeck/General/Private/RenderRequest.cpp
> +	FTextureRenderTargetResource*  rt_resource = TargetTexture->GetRenderTargetResource();
The variable "rt_resource" should follow the name convention that we have. RTResource maybe?

2018-06-12 03:02 UTC, mitchneutron commented on Source/Holodeck/General/Private/RenderRequest.cpp
> +		FIntPoint size;
These too. Variables need to be capitalized.

2018-06-12 03:02 UTC, mitchneutron commented on Source/Holodeck/General/Public/HolodeckViewportClient.h
> +	/**
We should make sure to document the public functions.

2018-06-12 03:02 UTC, mitchneutron commented on Source/Holodeck/General/Public/HolodeckViewportClient.h
> +	//void ClearNullCameras();
Clear out commented code

2018-06-12 03:02 UTC, mitchneutron commented on Source/Holodeck/General/Public/RenderRequest.h
> +// Adapted from Microsoft Airsim Open Source Project
I'm glad that you sited the source of inspiration!

2018-06-12 03:02 UTC, mitchneutron commented on Source/Holodeck/General/Public/RenderRequest.h
> +		void DoTask(ENamedThreads::Type CurrentThread, const FGraphEventRef& MyCompletionGraphEvent)
The code is very self documenting, which is good. We should still make sure to document the public functions though.

2018-06-12 03:02 UTC, mitchneutron commented on Source/Holodeck/Sensors/Public/HolodeckCamera.h
> +};
Newline here

2018-06-13 20:41 UTC, closed without merging

2018-06-13 20:41 UTC, nickwalton commented
Realized this branch is slightly corrected. Transferred changes to new branch and will create pull request there.